# Adapted from https://packaging.python.org/guides/supporting-windows-using-appveyor/

skip_non_tags: false  # we want to build untagged revisions.

version: "{branch}.{build}"  # Makes build version information more readable on appveyor

environment:
  matrix:
    # For Python versions available on Appveyor, see
    # https://www.appveyor.com/docs/windows-images-software/#python

    - PYTHON: "C:\\Python27"
      TESTTARGET: "test"

    - PYTHON: "C:\\Python27-x64"
      TESTTARGET: "test"

    - PYTHON: "C:\\Python27"
      TESTTARGET: "test_ui"

install:
    - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
    - "python --version"
    # We need wheel installed to build wheels
    - "python -m pip install wheel"
    - "python -m pip install pipwin"
    - "python -m pipwin install gdal"
    - "python -m pipwin install shapely"
    - "python -m pipwin install rtree"
    - "python -m pipwin install pyqt4"
    - "python -m pip install cython"
    - "python -m pip install numpy"
    - "python -m pip install -r requirements.txt -r requirements-dev.txt -r requirements-gui.txt"
    - "python setup.py sdist bdist_wheel"

    # Need to install with -I because pip thinks that cwd is a valid installation directory.
    # It's not (in our case).  Adding --no-deps because that's what all of the above
    # with pipwin and pip is for.
    - "python -m pip install -I --no-deps natcap.invest --find-links dist"
    - "choco install make"

build: off

test_script:
    - "make %TESTTARGET%"

artifacts:
    # bdist_wheel puts your built wheel in the dist directory
    - path: dist\*

# Cache-related items adapted from pyinstaller appveyor configuration.
# https://github.com/pyinstaller/pyinstaller/blob/develop/appveyor.yml
cache:
  # Cache downloaded pip packages and built wheels.
  - '%LOCALAPPDATA%\pip\Cache\http'
  - '%LOCALAPPDATA%\pip\Cache\wheels'
  - '%HOMEPATH%\pipwin'

on_finish:
  # Remove old or huge cache files to hopefully not exceed the 1GB cache limit.
  #
  # If the cache limit is reached, the cache will not be updated (of not even
  # created in the first run). So this is a trade of between keeping the cache
  # current and having a cache at all.
  - C:\cygwin\bin\find "%LOCALAPPDATA%\pip" -type f -mtime +360 -delete
  - C:\cygwin\bin\find "%LOCALAPPDATA%\pip" -empty -delete
  # Show size of cache
  - C:\cygwin\bin\du -hs "%LOCALAPPDATA%\pip\Cache"
