name: Run InVEST Tests

on: [push, pull_request, check_run]

jobs:
  Test:
    runs-on: ${{ matrix.os }}
    env:
        PACKAGES: "nose flake8"
    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        python-version: [3.6, 3.7]
        os: [ubuntu-16.04, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v1
    - name: setup-conda
      uses: s-weigand/setup-conda@v1.0.0
      with:
        update-conda: false
        python-version: ${{ matrix.python-version }}
        conda-channels: defaults
    - name: Install dependencies
      shell: bash
      run: |
          conda upgrade -y pip setuptools

    - name: Install InVEST (Windows)
      if: matrix.os == 'windows-latest'
      env:
          PIP_EXTRA_INDEX_URL: "http://pypi.naturalcapitalproject.org/simple/"
          PIP_TRUSTED_HOST: "pypi.naturalcapitalproject.org"
          PIP_PREFER_BINARY: 1
      shell: bash
      # Replace numpy and scipy with PyPI versions to circumvent import issue.
      # https://stackoverflow.com/a/37110747/299084
      run: |
          $CONDA/python -m pip install -r requirements.txt -r requirements-dev.txt
          $CONDA/python setup.py install

    - name: Install InVEST (Linux, Mac)
      if: matrix.os != 'windows-latest'
      run: |
          conda install --file requirements.txt
          conda install --file requirements-dev.txt
          python setup.py install

    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Validate Sample Data
      run: make validate_sampledata

    - name: Run model tests
      run: make test
